services:
  dev_app:
    container_name: vue_dev_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/workspace
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development