services:
  prod_app:
    container_name: vue_prod_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - NODE_ENV=production