services:
  dev_app:
    container_name: vue_dev_app
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
      - /workspace/node_modules
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=development